### ISSUE TITLE
metabinkit_blastgendb not creating db

### ISSUE THREAD

**Issue by bastianegeter** [envmetagen/metabinkit#23]
Hi Nuno,

probably a blast issue(?) but I get this error when trying to make a blast database on my laptop. I have seen it before on my laptop, but if you know what the issue might be it would be great to solve it!

I just tried on emg1 and it is fine! (fresh metabinkit installs on both machines)

```
$metabinkit_blastgendb -f SANGER_PLUS_GENBANK_CUT.fasta -o SANGER_PLUS_GENBANK_CUT_BLASTDB
metabinkit 0.1.7


Building a new DB, current time: 06/12/2020 12:49:44
New DB name:   /media/sf_Documents/WORK/CIBIO/AA_PROJECTS/IRANVERTS/SHEEP/SANGER_PLUS_GENBANK_CUT_BLASTDB
New DB title:  SANGER_PLUS_GENBANK_CUT.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Invalid argument
```

**Comment by nunofonseca** [comment]
Hi,
Yes, it is a BLAST error:
https://www.ncbi.nlm.nih.gov/books/NBK279684/
"If makeblastdb cannot access enough virtual memory, it will produce a message containing the string “mdb_env_open”. Virtual memory is just that (virtual) and doesn’t depend on the hardware in your system. In general, we recommend that BLAST users simply set the virtual memory to unlimited. The other alternative is to use an environment variable (BLASTDB_LMDB_MAP_SIZE) to set the required virtual memory lower, but this runs the risk of LMDB not being able to complete indexing the database."
Try before trying to generate the BLAST database
    export BLASTDB_LMDB_MAP_SIZE=1000000

**Comment by bastianegeter** [comment]
unfortunately this did not solve it for me. Maybe something to do with my virtualbox virtual machine.

**Comment by nunofonseca** [comment]
Yes, it looks like an issue related to the  virtual environment. Try to increase the VM resources or run makeblastdb in a docker image. Will close this issue since it is not a metabinkit issue per se but a Blast/VM one. If necessary we can discuss this on Slack.

**Comment by bastianegeter** [comment]
well, it appears this happens only when I try to write the database to the host machine shared folder. runs fine when I write to virtual machine hard disk!
