### ISSUE TITLE
Odd warning about taxid missing even though taxdb up to date

### ISSUE THREAD

**Issue by bastianegeter** [envmetagen/metabinkit#25]
See the readme: Example 2. Custom settings. The error is in the output:

`16:29:14.561 [WARN] taxid 2746931 not found`

`--SpeciesBL testspecies2exclude.txt` consist of 

```
$ cat testspecies2exclude.txt
6573
```

full command (using the files in metabinkit/tests/test_files)
`$ metabin -i in1.blast.short.tsv -o out1.blast.short.bins -S 98 -G 94 -F 93 -A 88 --SpeciesBL testspecies2exclude.txt --FilterFile Mioduchowska2018_flaggedAccessions.txt --FilterCol saccver --TopSpecies 2 --TopGenus 2 --TopFamily 2 --TopAF 2 --sp_discard_sp --sp_discard_mt2w --sp_discard_num`

**Comment by bastianegeter** [comment]
Hi, Still getting this. Seems to be an issue with taxonkit_children.sh I have added an example file /tests/test_files/taxids_18041cd18b62.txt

See the output below. taxid 2768769 is not in taxids_18041cd18b62.txt

perhaps the splitting of the file introduces gaps/empty lines?

```
[bastian.egeter@emg1 metabinkit]$ taxonkit_children.sh ./tests/test_files/taxids_18041cd18b62.txt ./tests/test_files/taxids_18041cd18b62.out /home/bastian.egeter/metabinkit.install/exe/../db/
20:26:10.694 [WARN] taxid 2768769 not found
20:26:12.957 [WARN] taxid 2768769 not found
20:26:15.273 [WARN] taxid 2768769 not found
```

**Comment by nunofonseca** [comment]
Hi, this issue is now solved (devel branch).
Cheers.
