### ISSUE TITLE
Add option to remove in-silico generated NCBI accessions

### ISSUE THREAD

**Issue by bastianegeter** [envmetagen/metabinkit#27]
Certain codes are used by NCBI to distinguish PREDICTED in-silico sequences. I wonder if we could add an option to remove these? The codes are XM_, XR_, XP_ so the option could be -rm_predicted [colname] something like

```
 if(length(grep("XM_.*",btab$colname))>0) btab<-btab[-grep("XM_.*",btab$colname),] 
  if(length(grep("XR_.*",btab$colname))>0) btab<-btab[-grep("XR_.*",btab$colname),] 
  if(length(grep("XP_.*",btab$colname))>0) btab<-btab[-grep("XP_.*",btab$colname),]  
```

**Comment by nunofonseca** [comment]
Option --rm_predicted added to the devel version.
