### ISSUE TITLE
NCBI: sometimes there are spaces in order, family, genus etc.

### ISSUE THREAD

**Issue by bastianegeter** [envmetagen/metabinkit#3]
Hi Nuno, 
I was just looking at mussels results and noticed that sometimes bacteria get weird designations

e.g. taxid 1884634 has the 7-level taxonomy of:
```
K | P | C | O | F | G | S
Bacteria | Actinobacteria | Actinobacteria | Candidatus Nanopelagicales | Candidatus Nanopelagicaceae | Candidatus Nanopelagicus | Candidatus Nanopelagicus limnes
```
Note the spaces at order, family, genus level (and two spaces at species level). This definitely annoys my other scripts. Honestly, I dont know how it will affect things here in the end, but I wanted to have it here as a note.

**Comment by bastianegeter** [comment]
file added metabinkit/tests/test_files/2019_August_002.UNIO.lenFilt.trimmed.ids.SC4.pol.blast.filt.txt , although here I have already replaced spaces with "_". You can grep "Candidatus_Nanopelagicales" to see examples. If you use taxonkit with taxid 1884634, you can also see what I mean. Below is a screenshot for this taxid from ncbi. Weird formatting in my opinion.

![image](https://user-images.githubusercontent.com/8413496/82909816-b07f5380-9f61-11ea-8ba3-4cbbe271af3f.png)

**Comment by bastianegeter** [comment]
Maybe this only happens for "Candidatus" entries. From wikipedia: 

Candidatus [1] is a term in the taxonomy (scientific classification) of bacteria.

It is a label put before the name of a bacterium which cannot be grown on an agar plate or in any other bacteriology culture. An example would be "Candidatus Phytoplasma allocasuarinae".[2] Candidatus status may be used when a species or genus is well studied but cannot be cultured. Nowadays much information is got by 16S ribosomal RNA sequence analysis.

**Comment by nunofonseca** [comment]
Thanks for the examples. It seems to be working...no?
 

> cut -f 1,2,3,4,5,6 tests/test_files/2019_August_002.UNIO.lenFilt.trimmed.ids.SC4.pol.blast.filt.txt > tests/test_files/in5.blast.tsv
>metabin -i tests/test_files/in5.blast.tsv -o .metabin.test.out -S 98 -G 95 -F 92 -A 80 --discard_sp -M
>grep "Candidatus" .metabin.test.out.tsv|head -n 1

      '7bd0a769-8719-4a26-8703-983667c7ec84_runid=407cb32920f83b2252d840c6a949244d8c2a3bb9_ss_sample_id=Mussels-ITD23-A-UNIO-RUN7      Bacteria        Candidatus Latescibacteria      unknown unknown NA      NA      NA'
